### ISSUE TITLE
Deserializing Yaml using .NET Core 2.0

### ISSUE THREAD

**Issue by jasongaylord** [aaubry/YamlDotNet#263]
I have a basic model called TestModel,
```
public class TestModel
{
    public string Title { get; set; }
}
```

really basic YAML,
```
---
title: Hello World!
---
```

and a very simple deserialize process:
```
var yaml = "---" + Environment.NewLine +
           "Title: Hello World!" + Environment.NewLine +
           "---";

var deserializer = new DeserializerBuilder()
    .WithNamingConvention(new CamelCaseNamingConvention()).Build();
var x = deserializer.Deserialize<TestModel>(yaml);
```

When I attempt to deserialize, I get the following error:
```
YamlDotNet.Core.YamlException occurred
  HResult=0x80131500
  Message=(Line: 2, Col: 1, Idx: 5) - (Line: 2, Col: 1, Idx: 5): Exception during deserialization
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at TestYaml.Program.Main(String[] args) in C:\Code\TestYaml\TestYaml\Program.cs:line 28

Inner Exception 1:
SerializationException: Property 'Title' not found on type 'TestYaml.TestModel'.
```

I've tried explicitly setting the Yaml property name in the model like so:
```
public class TestModel
{
    [YamlMember(Alias = "Title", ApplyNamingConventions = false)]
    public string Title { get; set; }
}
```

But then I get this:
```
YamlDotNet.Core.YamlException occurred
  HResult=0x80131500
  Message=(Line: 3, Col: 1, Idx: 26) - (Line: 3, Col: 4, Idx: 29): Expected 'StreamEnd', got 'DocumentStart' (at Line: 3, Col: 1, Idx: 26).
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at YamlDotNet.Core.ParserExtensions.Expect[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at TestYaml.Program.Main(String[] args) in C:\Code\TestYaml\TestYaml\Program.cs:line 28
```

I am running this under .NET Core 2.0.

**Comment by aaubry** [comment]
You are using `CamelCaseNamingConvention`, but your yaml uses
```
Title: Hello World!
```
Instead of
```
title: Hello World!
```

The other error is, as the exception indicates, because the parser encounters a document start, while it expected an end of stream. Your stream ends with a document start indicator, which is probably not what you want here.

**Comment by jasongaylord** [comment]
Got it. Sorry. Oversight on my part. Thanks!
