### ISSUE TITLE
Naming convention doesn't seem to work

### ISSUE THREAD

**Issue by ForNeVeR** [aaubry/YamlDotNet#281]
I'm trying to apply `PascalCaseNamingConvention` to the following small sample:

```csharp
using System;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace ConsoleApplication
{
    class Program
    {
        class Foo
        {
            public int Id { get; set; }
        }
        
        static void Main(string[] args)
        {
            const string text = "id: 123\n";
            var deserializer = new DeserializerBuilder()
                .WithNamingConvention(new PascalCaseNamingConvention())
                .Build();

            var foo = deserializer.Deserialize<Foo>(text);
            Console.WriteLine(foo.Id);
        }
    }
}
```

(I am using YamlDotNet 4.2.2-pre0425 on .NET Core 2.0)

It throws an exception:

```
Unhandled Exception: YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'id' not found on type 'ConsoleApplication.Program+Foo'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at ConsoleApplication.Program.Main(String[] args) in T:\Temp\ConsoleApplication\ConsoleApplication\Program.cs:line 21
```

No matter what `INamingConvention` I try to use, the outcome is always the same: it ends up looking for the property named `id`. Am I missing something, or is it a bug?

**Comment by ForNeVeR** [comment]
Sorry, it was mistake on my side. Naming convention actually works.

**Comment by Anton-V-K** [comment]
The problem here seems to be caused by `class Foo` being `private` by default.
