### ISSUE TITLE
Exception during deserialization: This operation is only valid on generic types.

### ISSUE THREAD

**Issue by miterosan** [aaubry/YamlDotNet#320]
Deserialization this yaml will throw this exception.

```
YamlDotNet.Core.YamlException: (Line: 2, Col: 3, Idx: 13) - (Line: 2, Col: 3, Idx: 13): 
Exception during deserialization ---> System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at YamlDotNet.Serialization.ObjectFactories.DefaultObjectFactory.Create(Type type)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at BTD.Agent.PlanInfo.PlanInfoParser.Parse(String yamlPlanInfo)
```

```yaml
building:
  artifacts:
    - output/
    - logs/*.binlog
  windows:
    script: scripts/build.ps1
  linux:
    script: scripts/build.linux.sh

testing: 
  windows:
    script: scripts/test.ps1
    results:
      - TestResults/*.trx 

enviromnent:
  validate:
    administrator: true
    windows:
      script: scripts/checkEnv.ps1
```

```csharp
            var deserializer =
                new DeserializerBuilder()
                    .WithNamingConvention(new CamelCaseNamingConvention())
                    .Build();

            return deserializer.Deserialize<ParsedPlanInfo>(yamlPlanInfo);
```

```xml
<TargetFramework>netcoreapp2.0</TargetFramework>
```

**Comment by miterosan** [comment]
Here is the full source: https://github.com/miterosan/BuildThenDeploy

**Comment by bonesoul** [comment]
were you able to come up a fix for this

**Comment by miterosan** [comment]
This happened with a old version of YamlDotNet. Now it works fine.
