### ISSUE TITLE
Throws System.Reflection.TargetException when serializing my object graph

### ISSUE THREAD

**Issue by ekolis** [aaubry/YamlDotNet#34]
Here's the stack trace - sorry I have no idea what in my object graph broke the serializer!

   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.TraverseGenericDictionary(Object value, Type type, Type dictionaryType, IObjectGraphVisitor visitor) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 154
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.TraverseObject(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 116
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.Traverse(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 94
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.SerializeProperties(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 197
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.TraverseObject(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 126
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.Traverse(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 94
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.SerializeProperties(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 197
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.TraverseObject(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 126
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.Traverse(Object value, Type type, IObjectGraphVisitor visitor, Int32 currentDepth) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 94
   at YamlDotNet.RepresentationModel.Serialization.FullObjectGraphTraversalStrategy.YamlDotNet.RepresentationModel.Serialization.IObjectGraphTraversalStrategy.Traverse(Object graph, Type type, IObjectGraphVisitor visitor) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\FullObjectGraphTraversalStrategy.cs:line 41
   at YamlDotNet.RepresentationModel.Serialization.Serializer.CreateEmittingVisitor(Emitter emitter, IObjectGraphTraversalStrategy traversalStrategy, IEventEmitter eventEmitter, Object graph, Type type) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\Serializer.cs:line 178
   at YamlDotNet.RepresentationModel.Serialization.Serializer.Serialize(Emitter emitter, Object graph, Type type) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\Serializer.cs:line 152
   at YamlDotNet.RepresentationModel.Serialization.Serializer.Serialize(Emitter emitter, Object graph) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\Serializer.cs:line 130
   at YamlDotNet.RepresentationModel.Serialization.Serializer.Serialize(TextWriter writer, Object graph) in d:\Work\YamlDotNet\YamlDotNet.RepresentationModel\Serialization\Serializer.cs:line 109
   at FrEee.Game.Objects.Space.Galaxy.SerializeGameState(Stream stream) in c:\Users\Ed\Documents\Visual Studio 2012\Projects\FrEee\FrEee\Game\Objects\Space\Galaxy.cs:line 170
   at FrEee.Game.Objects.Space.Galaxy.Save() in c:\Users\Ed\Documents\Visual Studio 2012\Projects\FrEee\FrEee\Game\Objects\Space\Galaxy.cs:line 234
   at FrEee.Game.Objects.Space.Galaxy.SaveAll() in c:\Users\Ed\Documents\Visual Studio 2012\Projects\FrEee\FrEee\Game\Objects\Space\Galaxy.cs:line 247
   at FrEee.Game.Objects.Space.Galaxy.Initialize(GameSetup gsu, Status status, Double desiredProgress) in c:\Users\Ed\Documents\Visual Studio 2012\Projects\FrEee\FrEee\Game\Objects\Space\Galaxy.cs:line 491
   at FrEee.WinForms.Forms.MainMenuForm.<>c__DisplayClass4.<btnQuickStart_Click>b__2() in c:\Users\Ed\Documents\Visual Studio 2012\Projects\FrEee\FrEee.WinForms\Forms\MainMenuForm.cs:line 82

**Comment by aaubry** [comment]
Closing this because the issue probably no longer exists. Please open a new issue if you still encounter this bug.

**Comment by linwrui** [comment]
I have came up against difficulties:"{"(Line: 1, Col: 1, Idx: 0) - (Line: 2, Col: 1, Idx: 122): Exception during deserialization"}"The innermessage said that there are some property can not find on the type.The quetion is why ,I'm sure that the property is on the type.Any one can answer me ?
