### ISSUE TITLE
Unable to use JSON-syntax after upgrade to 9.1.0

### ISSUE THREAD

**Issue by galvesribeiro** [aaubry/YamlDotNet#556]
Hello folks!

We've being using YamlDotNet 7.x.x for a while and never had an issue. We are now trying to update it to latest package because some new dependencies we have requires it. However, when we upgrade it to 9.1.0 it fail to deserialize an YAML that was working just fine.

Here is the snipped:

```yaml
  player:
    - {name: "John Doe" , level: 2}
```

> (Line: 2576, Col: 5, Idx: 76905) - (Line: 2576, Col: 5, Idx: 76905): Exception during deserialization

All we get from the exception is that. 

```
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)

<REDACTED>
   ```

As I said, it worked without problem before the upgrade and if we revert back to 7.x.x I can confirm it works just fine.

Can anyone advise on what is going on?

Thanks!

**Comment by galvesribeiro** [comment]
We've found the issue. In fact the JSON snipped I've posted is not a valid JSON. 

Changing it to this worked right away:

```yaml
  player:
    - {"name": "John Doe" , "level": 2}
```

The fact still stand. Even with the invalid JSON, the version 7.0.0 was able to deserialize it, while 9.1.0 can't.

I'll leave the issue open so the maintainers can decide whether or not they want to fix that.

Thanks!

**Comment by EdwardCooke** [comment]
I just checked this with the most recent version and it is working:

```csharp
using YamlDotNet.Serialization;

var yaml = @"player:
  - {name: ""John Doe"" , level: 2}
";
var deserializer = new DeserializerBuilder().Build();
var result = deserializer.Deserialize<object>(yaml);
var serializer = new SerializerBuilder().Build();
var s = serializer.Serialize(result);
Console.WriteLine(yaml);
Console.WriteLine("====");
Console.WriteLine(s);
```

Result
```text
player:
  - {name: "John Doe" , level: 2}

====
player:
- name: John Doe
  level: 2
```

I'm going to close this issue since it doesn't look like a problem any more.
