### ISSUE TITLE
Quoted strings longer than 128 result in SyntaxErrorException

### ISSUE THREAD

**Issue by Trojaner** [aaubry/YamlDotNet#578]
Here is an example file that breaks:

```yaml
# Configuration for Serilog
# This is the yaml equivalent of this https://github.com/serilog/serilog-settings-configuration
# For more see https://openmod.github.io/openmod-docs/userdoc/concepts/logging
Serilog:
  Using:
  - Serilog
  - Serilog.Sinks.Console
  - Serilog.Sinks.File
  - Serilog.Sinks.Async
  WriteTo:
  - Name: Async
    Args:
      configure:
      - Name: Console
        Args:
          theme: "Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme::Literate, Serilog.Sinks.Console"
          outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}][{SourceContext}] {Message:lj}{NewLine}{Exception}"
      - Name: File
        Args:
          path: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
          outputTemplate: "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}][{SourceContext}] {Message:lj}{NewLine}{Exception}"
  Enrich:
  - FromLogContext
  MinimumLevel:
    Default: Information
    Override:
      # You can configure when specific events should be logged
      # In this example, the Microsoft.EntityFrameworkCore events below are only logged if Warning or higher
      Microsoft.EntityFrameworkCore.Database.Command: Warning
      Microsoft.EntityFrameworkCore.Infrastructure: Warning
      Microsoft.EntityFrameworkCore.Database.Connection: Warning
      Microsoft.EntityFrameworkCore.Query: Warning
      # In case of verbose logging we still might want to have the event bus disabled as it spams a lot of logs
      OpenMod.Core.Eventing.EventBus: Information
```

```yaml
path: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
``` 
^ These 129 characters will break it, doesn't matter if using `"` or `'`. If using less than 128 characters it will work. 

The error is completely unrelated and it took quite a while to narrow it down:
```
YamlDotNet.Core.SyntaxErrorException: (Line: 26, Col: 5, Idx: 1023) - (Line: 26, Col: 5, Idx: 1023): While scanning a simple key, could not find expected ':'.
   at YamlDotNet.Core.Scanner.RemoveSimpleKey()
   at YamlDotNet.Core.Scanner.FetchStreamEnd()
   at YamlDotNet.Core.Scanner.FetchMoreTokens()
   at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming()
   at YamlDotNet.Core.Parser.GetCurrentToken()
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.RepresentationModel.YamlScalarNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlMappingNode.Load(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(IParser parser, DocumentLoadingState state)
   at YamlDotNet.RepresentationModel.YamlDocument..ctor(IParser parser)
   at YamlDotNet.RepresentationModel.YamlStream.Load(IParser parser)
   at NetEscapades.Configuration.Yaml.YamlConfigurationFileParser.Parse(Stream input)
```

**Comment by kbuzby** [comment]
@Trojaner - I tested out the file you have because I wanted to validate that this project would be useful for me in a case where we could easily expect strings longer than 128 characters.

With the following test project I didn't encounter any crashes:
```csharp
        private static int Main(string[] args)
        {
            var testData = @"# Configuration for Serilog
# This is the yaml equivalent of this https://github.com/serilog/serilog-settings-configuration
# For more see https://openmod.github.io/openmod-docs/userdoc/concepts/logging
Serilog:
  Using:
  - Serilog
  - Serilog.Sinks.Console
  - Serilog.Sinks.File
  - Serilog.Sinks.Async
  WriteTo:
  - Name: Async
    Args:
      configure:
      - Name: Console
        Args:
          theme: ""Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme::Literate, Serilog.Sinks.Console""
          outputTemplate: ""[{Timestamp:HH:mm:ss} {Level:u3}][{SourceContext}] {Message:lj}{NewLine}{Exception}""
      - Name: File
        Args:
          path: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
          outputTemplate: ""[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}][{SourceContext}] {Message:lj}{NewLine}{Exception}""
  Enrich:
  - FromLogContext
  MinimumLevel:
    Default: Information
    Override:
      # You can configure when specific events should be logged
      # In this example, the Microsoft.EntityFrameworkCore events below are only logged if Warning or higher
      Microsoft.EntityFrameworkCore.Database.Command: Warning
      Microsoft.EntityFrameworkCore.Infrastructure: Warning
      Microsoft.EntityFrameworkCore.Database.Connection: Warning
      Microsoft.EntityFrameworkCore.Query: Warning
      # In case of verbose logging we still might want to have the event bus disabled as it spams a lot of logs
      OpenMod.Core.Eventing.EventBus: Information";
            var serializer = new Deserializer();
            var A = serializer.Deserialize<Dictionary<string, object>>(testData);
            return 0;
        }
```

Seems like the issue might be resolved or could lie elsewhere?

**Comment by Trojaner** [comment]
Sorry, the issue was related to how we pre processed yaml files. It resulted in them getting truncated hence the error here. Forgot to close the issue.
