### ISSUE TITLE
YamlDotNet is not parsing anchors correctly

### ISSUE THREAD

**Issue by darkguy2008** [aaubry/YamlDotNet#627]
**Describe the bug**
Objects referencing anchors come out as null.

**To Reproduce**
```C#
using System.IO;
using YamlDotNet.Core;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace compiler
{
    class Program
    {
        static void Main(string[] args)
        {
            string yaml = @"
controls:
  - control: &panel1
    type: panel
    background: red

  - control: &panel2
    type: panel
    background: blue

structure:
  - *panel1
  - *panel2
            ";
            var ds = new DeserializerBuilder()
                .WithNamingConvention(CamelCaseNamingConvention.Instance)
                .IgnoreUnmatchedProperties()
                .Build();
            var f = ds.Deserialize<object>(
                new MergingParser(new Parser(new StringReader(yaml))));
        }
    }
}
```

**Result:** Structure items are null:

![image](https://user-images.githubusercontent.com/6304136/128805960-072931ff-dd6f-48e0-9eda-ced6c28dcc33.png)

Changing the structure to:
```yaml
structure:
  - <<: *panel1
  - <<: *panel2
```
Throws an exception:
```
Exception has occurred: CLR/System.Collections.Generic.KeyNotFoundException
An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in System.Private.CoreLib.dll: 'The given key 'panel1' was not present in the dictionary.'
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at YamlDotNet.Core.MergingParser.ParsingEventCollection.FromAnchor(AnchorName anchor)
   at YamlDotNet.Core.MergingParser.GetMappingEvents(AnchorName anchor)
   at YamlDotNet.Core.MergingParser.HandleAnchorAlias(LinkedListNode`1 node, LinkedListNode`1 anchorNode, AnchorAlias anchorAlias)
   at YamlDotNet.Core.MergingParser.HandleMerge(LinkedListNode`1 node)
   at YamlDotNet.Core.MergingParser.Merge()
   at YamlDotNet.Core.MergingParser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.Accept[T](IParser parser, T& event)
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
```

**Expected result**

Structure should contain the same items shown in the Controls key in the screenshot above.

**Comment by EdwardCooke** [comment]
This makes sense. The anchor is set to the content of `control`. Which is empty. And according to yaml spec, empty means null.

The following YAML:
```yaml
controls:
  - control: &panel1 hello1
    type: panel
    background: red

  - control: &panel2 hello2
    type: panel
    background: blue

structure:
  - *panel1
  - *panel2
```
Looks like this:
![image](https://user-images.githubusercontent.com/81339027/179451459-a6f45704-3e03-405a-aeb8-5016758f3bb5.png)

The following yaml
```yaml
controls:
  - &panel1
    control: hello1
    type: panel
    background: red

  - &panel2
    control: hello2
    type: panel
    background: blue

structure:
  - *panel1
  - *panel2
```
looks like this:

![image](https://user-images.githubusercontent.com/81339027/179451671-38216f59-49f6-4db7-9ac1-c78f223f9291.png)

I'm going to close this issue. If you need more assistance, or disagree, feel free to reopen it.
