### ISSUE TITLE
Special string triggers SemanticErrorException: Invalid key indicator format

### ISSUE THREAD

**Issue by stakira** [aaubry/YamlDotNet#719]
**Describe the bug**
Round trip of certain plain strings is handled incorrectly.
May be similar to #709.
Version: 12.0.0

**To Reproduce**
```
  var serializer = new YamlDotNet.Serialization.SerializerBuilder().Build();
  string yaml = serializer.Serialize(new System.Collections.Generic.Dictionary<string, string>() {
      { "symbol_1", "-@" },
      { "symbol_2", "-&" }
  });
  var deserializer = new YamlDotNet.Serialization.DeserializerBuilder().Build();
  var dict = deserializer.Deserialize<System.Collections.Generic.Dictionary<string, string>>(yaml);
```
```
YamlDotNet.Core.SemanticErrorException
  HResult=0x80131500
  Message=Invalid key indicator format.
  Source=YamlDotNet
  StackTrace:
   at YamlDotNet.Core.Parser.ParseNode(Boolean isBlock, Boolean isIndentlessSequence)
   at YamlDotNet.Core.Parser.ParseBlockMappingValue()
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
```

**Comment by EdwardCooke** [comment]
This is the same bug as #709. I am waiting for pull request #710 to be updated with the new values. I made that check to *strict* when getting it to pass the new YAML tests.

Once that PR is done I'll close that issue and this one.
